PackageName: "AMD"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
